// src/components/ExpressionNode.tsx
import { For, Switch, Match } from "solid-js";

import type { Expression, EKind } from "~/parser/parser";
import { type TreeState } from "~/editor/tree";

import "./ExpressionNode.css";

export type NodeProps = {
  node: Expression,
  tree: TreeState,
  path: number[],
}

type NodePropsLimitedTo<T> = Omit<NodeProps, 'node'> & { node: EKind<T> };

export default function Node(props: NodeProps) {
  const selected = () => props.tree.selection.path().length == props.path.length &&
                       props.tree.selection.path().every((v,i) => props.path[i] == v);

  const onClick = (ev: MouseEvent) => {
    props.tree.selection.setPath(props.path);
    ev.stopPropagation();
  }

  return (
    <div style={{"--depth": props.path.length}}
         classList={{selected: selected()}}
         onClick={onClick}>
      <NodeContent {...props} />
    </div>
  )
}

export function NodeContent(props: NodeProps) {
  return (
    <Switch fallback={<Placeholder />}>
      <Match when={props.node.kind == "operator"}>
        <Operator {...props as any}/>
      </Match>
      <Match when={props.node.kind == "funCall"}>
        <FunCall {...props as any}/>
      </Match>
      <Match when={props.node.kind == "ident" || props.node.kind == "number" || props.node.kind == "unknown"}>
        <Value {...props as any}/>
      </Match>
    </Switch>
  );
}

const Placeholder = () => <div class="node leaf placeholder"></div>;

function Value(props: NodePropsLimitedTo<'number' | 'ident' | 'unknown'>) {
  return (
    <div classList={{node: true, leaf: true, [props.node.kind]: true}}>
      {props.node.value}
    </div>
  )
}

function Operator(props: NodePropsLimitedTo<'operator'>) {
  let value = props.node.op as string;
  let extraStyle: string = "";
  let between: string = "";
  switch (props.node.op) {
    case "unknown":
      value = "";
      extraStyle = "placeholder";
      break;
    case ".":
      value = "";
      extraStyle = "indexList";
      between = ".";
      break;
    default:
      if (props.node.parenthesized) value = '(' + value + ')';
  }
  return (
    <div classList={{node: true, operator: true, [extraStyle]: true}}>
      <div class="op">{value}</div>
      <div class="children">
        <For each={props.node.children}>
          {(child, index) =>
            <>
              <Node {...props} path={[...props.path, index()]} node={child} />
              {index() != props.node.children.length-1 ? between : ''}
            </>
          }
        </For>
      </div>
    </div>
  );
}

function FunCall(props: NodePropsLimitedTo<"funCall">) {
  return (
    <div class="node funCall">
      <Node {...props} path={[...props.path, 0]} node={props.node.value[0]} />
      (
      <div class="args">
        <For each={props.node.value.slice(1)}>
          {(child, index) =>
            <Node {...props} path={[...props.path, index()+1]} node={child} />
          }
        </For>
      </div>
      )
    </div>
  )
}

// src/routes/editor/ExpressionNode.svelte
<script lang="ts">
 import type { Expression } from "./parser";

 export let root: Expression;
 export let treePath = [];

 type NodeInfo = {
     value: string,
     children?: Expression[],
     args?: Expression[],
     extraStyle?: string,
 };

 function getNodeInfo(node: Expression): NodeInfo {
     switch (node.kind) {
         case "number":
         case "ident":
             return {value: String(node.value)};
         case "operator": {
             let value = node.op;
             let extraStyle;
             switch (node.op) {
                 case "unknown":
                     value = "";
                     extraStyle = "unknown";
                     break;
                 case ".":
                     value = "";
                     extraStyle = "indexList";
                     break;
                 default:
                     if (node.parenthesized) value = '(' + value + ')';
             }
             return {
                 value,
                 children: node.children,
                 extraStyle,
             }
         }
         case "funCall": return {
             value: "",
             children: [node.value[0]],
             args: node.value.slice(1),
         };
         case "placeholder": return {
             value: "",
         };
     }
 }

 let info;
 $: info = getNodeInfo(root);
</script>

<div style:background={`lch(${info.children ? 30 : 40}% 45 ${treePath.length*40+20}`}
     class="node {root.kind} {info.extraStyle}"
>
    <div class="value">{info.value}</div>
    {#if info.children}
        <p class="children">
        {#each info.children as child, index}
            <svelte:self root={child} treePath={[...treePath, index]}/>
            {root.op == "." && index < info.children.length-1 ? '.' : ''}
        {/each}
        {#if info.args}
            (
            <div class="args">
                {#each info.args as arg, index}
                    <svelte:self root={arg} treePath={[...treePath, index+1]}/>
                {/each}
            </div>
            )
        {/if}
        </p>
    {/if}
</div>

<style>
 @import "./ExpressionNode.css";
</style>
